name: Build and Push Image

on:
  push:
    branches:
      - '**'      # 모든 브랜치
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract branch + build tag
        id: meta
        run: |
          BRANCH="${GITHUB_REF_NAME}"
          # GitHub Actions의 run 번호를 빌드번호로 사용 (브랜치별 증가 보장은 안 되지만 간단)
          TAG="${BRANCH}-${GITHUB_RUN_NUMBER}"
          echo "branch=${BRANCH}" >> $GITHUB_OUTPUT
          echo "tag=${TAG}" >> $GITHUB_OUTPUT

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:${{ steps.meta.outputs.tag }}
          labels: |
            org.opencontainers.image.source=${{ github.repository }}

      - name: Show image tag
        run: echo "pushed ghcr.io/${{ github.repository }}:${{ steps.meta.outputs.tag }}"
